apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-ad-api
  labels:
    app: game-ad-service
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: game-ad-service
      component: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: game-ad-service
        component: api
    spec:
      containers:
      - name: api
        image: game-ad-service:latest
        imagePullPolicy: IfNotPresent
        command: ["./api-server"]
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: PORT
          value: "8080"
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        - name: REDIS_ADDRESS
          value: "redis:6379"
        - name: CACHE_TYPE
          value: "redis"
        - name: PERSISTENCE_TYPE
          value: "memory"
        - name: QUEUE_CAPACITY
          value: "10000"
        - name: MAX_ATTEMPTS
          value: "3"
        - name: PROCESSING_TIMEOUT
          value: "5m"
        - name: LOCK_TTL
          value: "30"
        - name: MIN_WORKERS
          value: "1"
        - name: MAX_WORKERS
          value: "2"
        - name: ENABLE_AUTO_SCALE
          value: "true"
        - name: TARGET_QUEUE_SIZE
          value: "10"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: game-ad-api
  labels:
    app: game-ad-service
    component: api
spec:
  selector:
    app: game-ad-service
    component: api
  ports:
  - port: 80
    targetPort: http
    name: http
  type: ClusterIP 