apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: game-ad-service
    component: redis
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: game-ad-service
      component: redis
  template:
    metadata:
      labels:
        app: game-ad-service
        component: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 30
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 3
          periodSeconds: 10
        volumeMounts:
        - name: redis-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: game-ad-service
    component: redis
spec:
  selector:
    app: game-ad-service
    component: redis
  ports:
  - port: 6379
    targetPort: redis
    name: redis
  clusterIP: None 