apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-ad-worker
  labels:
    app: game-ad-service
    component: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: game-ad-service
      component: worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: game-ad-service
        component: worker
    spec:
      containers:
      - name: worker
        image: game-ad-service:latest
        imagePullPolicy: IfNotPresent
        command: ["./worker-server"]
        env:
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        - name: REDIS_ADDRESS
          value: "redis:6379"
        - name: CACHE_TYPE
          value: "redis"
        - name: PERSISTENCE_TYPE
          value: "memory"
        - name: QUEUE_CAPACITY
          value: "10000"
        - name: MAX_ATTEMPTS
          value: "3"
        - name: PROCESSING_TIMEOUT
          value: "5m"
        - name: LOCK_TTL
          value: "30"
        - name: MIN_WORKERS
          value: "5"
        - name: MAX_WORKERS
          value: "15"
        - name: MAX_CONCURRENT_JOBS
          value: "0"
        - name: ENABLE_AUTO_SCALE
          value: "true"
        - name: TARGET_QUEUE_SIZE
          value: "100"
        resources:
          limits:
            cpu: "1000m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "256Mi"
      terminationGracePeriodSeconds: 60 